language: cpp
git:
    submodules: true

matrix:
    include:
      - os: linux
        before_install:
          - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
          - sudo apt-get update -qq
        install:
          - sudo apt-get -y install qt59base
          - source /opt/qt*/bin/qt*-env.sh
        dist: trusty
        sudo: required
        addons:
            apt:
                packages:
                   - libjack-dev
                   - librtmidi-dev
                   - libsdl2-dev
                   - libzzip-dev
        script: &cmake_build
          - mkdir build
          - pushd build
          - cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 ..
          - cmake --build .
          - cpack
          - popd
          - qmake CONFIG+=release PREFIX=/usr
          - make -j$(nproc)
          - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
          - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
          - ls -a
          - cd /build/
          - ls -a
          - cp ./resources/*.desktop /appdir/usr/share/applications/
          - cp ./resources/pictures/milkytracker.png /appdir/usr/share/applications/
          - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
          - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
          - ./linuxdeployqt-continuous-x86
        after_success:
          - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
          - # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
          - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
          - bash upload.sh APPNAME*.AppImage*
          
      - os: osx
        before_install:
          - brew update
          - brew install xmlto
          - pushd resources/pictures/docicons/osx
          - wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/docerator/docerator-2.0.zip
          - unzip docerator-2.0.zip -d docerator
          - rm docerator-2.0.zip
          - /usr/bin/python genicons.py
          - popd
        script: *cmake_build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Vr2TAgHrYnMp95PUmGnzl3E2dMqBTe3E/JZZAInWC8Ifx1hCF0SI085svFg902kFhnZJhMFBukP/hNu6UAm/exTdAByks57Af9oJTCxrUIYhYs2sasKjmSKPjRD5rFB+zqZSlq/DKzQZTBZBYUn2w3f4otrbNB6vBayNgWMtKdEtS1GI6e9pxKQcvxJodi/4RNgws6l5sQ59aPSPGK0XnOSLu5HPGC4QLpdQVSw5/Rzn5Fcw3zPVYOs7ZV/t7ptmR7T+MjFSE7HBMJlUPflHWA+L3jjx8ngYkz+W0pNsXxomRQVCLhGlGo0F6EEijOt1TvLhqMTVWrMgNjK9pxlgZEMWTho8/44kLQ5ABGuqql+uhTtJXI4dLmrrSPnCDHvVd7j8cwQDptYvRaEhzZmxNAB+xhqWdMDzkL7DouRcFzuKWTCWPFablVDXElcODO+xqWcU62gO/xEww7Y1mC9GC5zpmOgA7198JxeIM/o5eiMsj1J24KK+2WJH3t65hqGNhRfHgoR24LfkylhU+MFEnM5ZQM/21IGfeA/bszKDitDfIuNMOCSQqiD/fIKFsqOrKRvMi5cp1XvHzQTIR5x+BWS6zQwQk0RCaM7d7FKTtT3w0cm0aNAD3f0MfdU3BKH9YG5DT5DNvsoP613bg50tVgarTX5PwNOosQU/rSysLIg=
  file_glob: true
  file: build/milkytracker-*
  on:
    tags: true
